### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by RicoP** [kevinmoran/GJK#1]
Hi there~ 

Are you planing to add a license to this project so others might can use your code for their own project? 

Personally I would appreciate a very liberal license like MIT :)

**Comment by kevinmoran** [comment]
Hey! Didn't expect any interest in using this, it's my first attempt at implementing the algorithm and is mostly intended as a reference if people are interested in doing the same! I'm more than happy to add a liberal license, with the disclaimer that I can make no guarantees that there are no bugs, and I haven't tested the performance in a non-trivial example. e.g. I remember that the way I handle the tetrahedral case is technically incomplete, but "good enough" for my  purposes.

 I'll use the license from STB libraries; i.e. dual-licensed under public domain and MIT. If you use it do let me know of any issues you find.

**Comment by RicoP** [comment]
Cool~ I just needed some reference for my own implementation, but I wanted to be on the safe side. If I run into issues I will let you know~
